[package]
name = "staves"
version = "0.1.0"
entrypoint = "src/lib.typ"
authors = [ "Matthew Davis" ]
license = "MIT"
description = "Draw musical clefs and key signatures."
keywords = [
  "Music",
  "Clef",
  "Treble",
  "Bass",
  "Alto",
  "Tenor",
  "Flat",
  "Sharp",
  "Key",
  "Accidental",
  "Score",
  "Stave",
  "Chord"
]
categories = [ "components", "visualization", "fun" ]
disciplines = [ "music" ]
exclude = [ "examples/", "examples/*", "docs/", "docs/*" ]
