[package]
name = "staves"
version = "0.1.0"
entrypoint = "src/lib.typ"
authors = ["Matthew Davis"]
description = "Draw musical clefs and key signatures."
homepage = "https://github.com/mdavis-xyz/staves-typst"
repository = "https://github.com/mdavis-xyz/staves-typst"
keywords = [
    "Music",
    "Clef",
    "Treble",
    "Bass",
    "Alto",
    "Tenor",
    "Flat",
    "Sharp",
    "Key",
    "Accidental",
    "Score",
    "Stave",
    "Chord",
]
categories = [
    "components",
    "visualization",
    "fun",
]
disciplines = ["music"]

[tool]
